name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        env:
          CI: true
      - name: Build package
        run: npm build
      - name: Test package
        run: npm test
      - name: Lint package
        run: npm run lint
